### ISSUE TITLE
"Further Reading" Footer Bar Doesn't Behave with Single-Window Navigation

### ISSUE THREAD

**Issue by CodeforEvolution** [humdingerb/quicktour#10]
While testing out your QuickTour online, I noticed that when I used the "non-slideshow" single page view, the bar at the bottom displays further reading options that correlate to the slide that would usually show package management related information.

Should the bottom bar "further reading" info change automatically as one scrolls down the page? Or should it just be hidden during single-window mode?

**Comment by humdingerb** [comment]
The QuickTour package in the HaikuDepot should be OK. I take it you checked out and seen this from this repo master?

Funny, you mention this right now. We wanted to put the QuickTour into the userguide translation site for easier managment. A few hours ago @waddlesplash and I decided to do that now, to get the translations started.

There will only be the single-page document. The navigational bar at the top and the further-reading bar at the bottom are to be updated according to where in the page we are. @waddlesplash will be working on the necessary css.
If you can help, try reaching him on IRC.

I'm about to enter the QuickTour into the translation site. I created a branch "welcomepkg" with the basis for that.

**Comment by CodeforEvolution** [comment]
Oh, cool! See, I tried it out before utilizing the link you posted in the readme. I guess I tried your guide accidentally in a transitional phase. :)

**Comment by humdingerb** [comment]
Everything's alright then. :)
The QuickTour is now ready for translation at the user guide online tool. The CSS etc. will have to be tweaked though, but the translation work can start.
